//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicamentoCLS", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceMedico.Class")]
    public partial class MedicamentoCLS : object
    {
        
        private int IIdMedicamentoField;
        
        private string nombreField;
        
        private string concentracionField;
        
        private decimal PrecioField;
        
        private int stockField;
        
        private string presentacionField;
        
        private int habilitadoField;
        
        private int iidFormaFarmaceuticaField;
        
        private string nombreFormaFarmaceuticaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IIdMedicamento
        {
            get
            {
                return this.IIdMedicamentoField;
            }
            set
            {
                this.IIdMedicamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string concentracion
        {
            get
            {
                return this.concentracionField;
            }
            set
            {
                this.concentracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string presentacion
        {
            get
            {
                return this.presentacionField;
            }
            set
            {
                this.presentacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int habilitado
        {
            get
            {
                return this.habilitadoField;
            }
            set
            {
                this.habilitadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int iidFormaFarmaceutica
        {
            get
            {
                return this.iidFormaFarmaceuticaField;
            }
            set
            {
                this.iidFormaFarmaceuticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string nombreFormaFarmaceutica
        {
            get
            {
                return this.nombreFormaFarmaceuticaField;
            }
            set
            {
                this.nombreFormaFarmaceuticaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaFarmaceuticaCLS", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceMedico.Class")]
    public partial class FormaFarmaceuticaCLS : object
    {
        
        private string NombreField;
        
        private int habilitadoField;
        
        private int iidFormafarmaceuticaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int habilitado
        {
            get
            {
                return this.habilitadoField;
            }
            set
            {
                this.habilitadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iidFormafarmaceutica
        {
            get
            {
                return this.iidFormafarmaceuticaField;
            }
            set
            {
                this.iidFormafarmaceuticaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulo", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceMedico.Class")]
    public partial class Articulo : object
    {
        
        private string DescripcionField;
        
        private int IdArticuloField;
        
        private int IdMarcaField;
        
        private string SkuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArticulo
        {
            get
            {
                return this.IdArticuloField;
            }
            set
            {
                this.IdArticuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMarca
        {
            get
            {
                return this.IdMarcaField;
            }
            set
            {
                this.IdMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceHospital")]
    public interface IServiceHospital
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/listarMedicamento", ReplyAction="http://tempuri.org/IServiceHospital/listarMedicamentoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MedicamentoCLS[]> listarMedicamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/listarFormaceutica", ReplyAction="http://tempuri.org/IServiceHospital/listarFormaceuticaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FormaFarmaceuticaCLS[]> listarFormaceuticaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/recuperarMedicamento", ReplyAction="http://tempuri.org/IServiceHospital/recuperarMedicamentoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MedicamentoCLS> recuperarMedicamentoAsync(int iiMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/agregarYActualizarMedicamento", ReplyAction="http://tempuri.org/IServiceHospital/agregarYActualizarMedicamentoResponse")]
        System.Threading.Tasks.Task<int> agregarYActualizarMedicamentoAsync(ServiceReference1.MedicamentoCLS medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/eliminarMeidcamento", ReplyAction="http://tempuri.org/IServiceHospital/eliminarMeidcamentoResponse")]
        System.Threading.Tasks.Task<int> eliminarMeidcamentoAsync(int iidMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/recuperaArticulo", ReplyAction="http://tempuri.org/IServiceHospital/recuperaArticuloResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Articulo> recuperaArticuloAsync(int iiArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHospital/listarArticulo", ReplyAction="http://tempuri.org/IServiceHospital/listarArticuloResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Articulo[]> listarArticuloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceHospitalChannel : ServiceReference1.IServiceHospital, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceHospitalClient : System.ServiceModel.ClientBase<ServiceReference1.IServiceHospital>, ServiceReference1.IServiceHospital
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceHospitalClient() : 
                base(ServiceHospitalClient.GetDefaultBinding(), ServiceHospitalClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceHospital.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceHospitalClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceHospitalClient.GetBindingForEndpoint(endpointConfiguration), ServiceHospitalClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceHospitalClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceHospitalClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceHospitalClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceHospitalClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceHospitalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MedicamentoCLS[]> listarMedicamentoAsync()
        {
            return base.Channel.listarMedicamentoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FormaFarmaceuticaCLS[]> listarFormaceuticaAsync()
        {
            return base.Channel.listarFormaceuticaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MedicamentoCLS> recuperarMedicamentoAsync(int iiMedicamento)
        {
            return base.Channel.recuperarMedicamentoAsync(iiMedicamento);
        }
        
        public System.Threading.Tasks.Task<int> agregarYActualizarMedicamentoAsync(ServiceReference1.MedicamentoCLS medicamento)
        {
            return base.Channel.agregarYActualizarMedicamentoAsync(medicamento);
        }
        
        public System.Threading.Tasks.Task<int> eliminarMeidcamentoAsync(int iidMedicamento)
        {
            return base.Channel.eliminarMeidcamentoAsync(iidMedicamento);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Articulo> recuperaArticuloAsync(int iiArticulo)
        {
            return base.Channel.recuperaArticuloAsync(iiArticulo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Articulo[]> listarArticuloAsync()
        {
            return base.Channel.listarArticuloAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceHospital))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceHospital))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55891/ServiceHospital.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceHospitalClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceHospital);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceHospitalClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceHospital);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceHospital,
        }
    }
}
